jobs:
  - name: hello
    plan:
    - task: talk
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: echo
          args: ['Hello Dogpatch!']

